### ISSUE TITLE
setScrollOffsetRatio makes scrolling and zooming problematic

### ISSUE THREAD

**Issue by TimPushkin** [p-lr/MapCompose#80] opened 2022-11-04 17:49 UTC
I'm using `setScrollOffsetRatio()` to get map padding as I was advised in #65 and, as I was also warned there, I'm having issues with zooming and scrolling when the map is fully (or nearly fully) zoomed out.

In all demonstration videos below I used `setScrollOffsetRatio(0.5f, 0.5f)`. They are all captured on an emulator but I get the same behavior on a real device.
 
1. When the map is fully zoomed out its scrolling is symmetrically constrained along the smaller layout dimension and unsymmetrically along the larger dimension. As can be seen in the video below, I can scroll the map half its size out of the screen horizontally in both directions, but vertically I can only do it at the bottom and not at the top.

https://user-images.githubusercontent.com/71890197/200036116-46fec103-f82b-4669-9ed5-3dcdb7b4a3b1.mp4

2. The video above also demonstrates an issue with `InitialValues.scroll()`. There it was set to `scroll(0.5, 0.5)`, which is meant to initially center the map, but it appears at the bottom of the screen instead. Setting it to `scroll(0.0, 0.0, Offset(0f, 0f))` (which is the default) actually centers the map.
3. When the map doesn't fully cover the screen, zooming seems to center somewhere at the bottom instead of where the gesture is actually centered. In the next video I'm zooming precisely into the center of the screen, but instead the zoom centers on a point on the bottom edge of the map. I think that the map tries to first fill the screen (which is reasonable) and then zoom where the user wants, but there is some error in calculations and it ends up at the bottom edge instead. Such behavior is very inconvenient, it is present both when zooming with pinch and with double-tap-and-drag.

https://user-images.githubusercontent.com/71890197/200037629-ac64ff53-e00d-4b5e-9f3a-eb6f6a4dc084.mp4

4. `centerOnMarker()` doesn't actually place the marker in the center of the layout when the map is zoomed out. In the video below I used the default "Center on marker" demo but changed the scale to 0 and enabled `scrollOffsetRatio`.

https://user-images.githubusercontent.com/71890197/200038996-39db788b-4c62-4768-b6dd-bcb03af135a9.mp4

**Comment by p-lr** [comment] 2022-11-04 18:25
Thanks for the precise description.
The scroll offset ratio is only partially supported at the moment. Having a proper support will require deep investigation for each cases (marker apis, gestures, etc).

**Comment by TimPushkin** [comment] 2022-11-04 18:32
Thanks for the reply, I assumed so, but wanted to highlight the issues. For me the third one (the issue with zooming) is the most annoying, because I cannot find a workaround for it.

**Comment by TimPushkin** [comment] 2022-11-04 18:37
I actually tried to look into each of them but only managed to find a solution for the first for now

**Comment by p-lr** [comment] 2022-11-04 18:42
If you manage to solve these issues, that means you get a thorough understanding of the library (or at least the "view" part). And solving the first one is already a good sign!

**Comment by p-lr** [comment] 2022-11-04 18:45
If you don't solve the other ones, no worry. I believe I'll start investigate in a few days.

**Comment by p-lr** [comment] 2022-11-16 16:23
@TimPushkin I need to finish some ongoing work before looking into this issue.

**Comment by p-lr** [comment] 2022-11-20 09:29
So I've started to look in this. And I noticed that when scroll offset ratio is set, all the mentioned issues are caused by the padding applied by the layout when the map is fully zoomed out. In the branch `try-fix-#80`, I disabled it. From my testing, that fixes the mentioned issues. Can you confirm?

**Comment by TimPushkin** [comment] 2022-11-20 10:31
I've tested it and indeed zoom works perfectly now!

But the issue with unsymmetrical scroll constraints along the larger dimension now appears again. Below I used `setScrollOffsetRatio(0.5f, 0.5f)`:
1. Maximum scroll to the bottom:
![image](https://user-images.githubusercontent.com/71890197/202897011-f50b37b3-42ae-4b74-97cf-03b347bef9cf.png)
2. Maximum scroll to the top:
![image](https://user-images.githubusercontent.com/71890197/202897035-79860de6-35e7-42d1-b992-b3047aa62d5b.png)

**Comment by p-lr** [comment] 2022-11-20 11:04
That's interesting, good catch !
If I revert the changes you introduced to fix unsymmetrical scroll, it seems to work.

**Comment by p-lr** [comment] 2022-11-20 13:22
IIUC, the changes you introduced were only applicable when layout padding wad applied. However, now that I disabled it (when `setScrollOffsetRatio` is used), it's no longer needed.
I've updated the `try-fix-#80` branch.

**Comment by TimPushkin** [comment] 2022-11-20 14:23
I tried reverting my changes, but this still doesn't work as expected. If I apply `setScrollOffsetRatio(0.5f, 0.5f)` I expect to be able to scroll the map half its size off the screen and this is what I get along the smaller layout dimension. But along the larger dimension I just cannot scroll the map off the screen:
1. Maximum scroll to the bottom:
![image](https://user-images.githubusercontent.com/71890197/202907452-e2e467f5-aa7e-44fd-a55c-2535c207dc3f.png)
2. Maximum scroll to the top:
![image](https://user-images.githubusercontent.com/71890197/202907430-625c084c-dd1a-461e-8d21-0957d337deb2.png)

**Comment by p-lr** [comment] 2022-11-20 16:06
It's ok, your changes fixed some aspects of the issue. However, I thought this issue would require a lot of non trivial changes. In the end, this is really good news.
As usual, thanks for your feedback and testing!

**Comment by p-lr** [comment] 2022-11-20 16:29
Ha.. I knew it was too easy. When rotation is enabled along with `setScrollOffsetRatio(0.5f, 0.5f)`, rotating the map behaves strangely.

**Comment by TimPushkin** [comment] 2022-11-20 16:55
Yep, all issues stay when the map is rotated

**Comment by p-lr** [comment] 2022-11-23 09:43
I created another branch named `try-fix-#80-attempt-2`, in which I changed fundamental canvas transformations.
This issue shows that there's something wrong, when :
- scroll offset ratio is set
- the map is scrolled out beyound `MinimumScaleMode.Fill` scale

A core design choice of the library is to always rotate
around the center of the screen. This allows for simpler calculations of the scroll. However, rotation could be handled 
differently, in theory. Maybe in a future major version, I'll change that to rotate around the focal point (even though
at this point I'm not sure at all that would result in a good behavior, especially when scroll offset ratio is set).

However in this branch, I didn't break core design, otherwise the whole ui part of the library would have to be re-written.
The end result is a compromise, maybe good enough.
One example of downside when `setScrollOffsetRatio(0.5f, 0.5f)` is used: the map isn't centered in the screen when fully zoomed out, unless `scroll(0.5, 0.5)` is used on MapState initial values. This is due to the layout padding disable.

**Comment by TimPushkin** [comment] 2022-11-23 10:11
Tried it, indeed now zooming and scrolling work great when `setScrollOffsetRatio()` is set to values large enough. But it seems like it is impossible to center the map at all (even with manual scrolling) when the values are small, (0.1, 0.1), for example. For me personally it's ok since I use (0.5, 0.5).

Now it's also easier to rotate the map partially off the screen when `setScrollOffsetRatio()` is not used, but since this is what `scrollOffsetRatio` is for, it doesn't seem like an issue to me.

**Comment by p-lr** [comment] 2022-11-23 10:16
Exactly, this is the drawback. If don't find a better alternative, the documentation of `setScrollOffsetRatio()` should recommend using (0.5, 0.5) when possible.

**Comment by TimPushkin** [comment] 2022-11-23 10:20
Played around with non-square maps and it seems like it is related to non-symmetrical scroll constraints again. Here I use `setScrollOffsetRatio(0.5f, 0.5f)` and the map is 4096x2048:

1. Maximum scroll to the top:
![image](https://user-images.githubusercontent.com/71890197/203522463-93b40758-71ad-4285-a806-9faec9c6c3a1.png)


2. Maximum scroll to the bottom:
![image](https://user-images.githubusercontent.com/71890197/203522385-ca33b1e2-dbcb-4f9d-8d79-cdec6cba7120.png)

**Comment by p-lr** [comment] 2022-11-23 13:15
In my last commit, I'm experimenting another approach. When fully zoomed out, if we allow more scroll than would otherwise be permitted by `setScrollOffsetRatio()`, we can produce a centering effect (even if the padding is disabled).
I found that if works for non square maps and also for other values than (0.5, 0.5).

**Comment by TimPushkin** [comment] 2022-11-24 08:09
Tried it, feels pretty good to me now

**Comment by p-lr** [comment] 2022-11-24 11:01
Thanks. I found some minor issues with this approach, and I'm still trying to fix them.

**Comment by p-lr** [comment] 2022-11-24 13:01
Out of curiosity, do you intend to enable rotation along with `setScrollOffsetRatio()`?

**Comment by TimPushkin** [comment] 2022-11-24 13:43
Yes, I do

**Comment by p-lr** [comment] 2022-11-26 20:10
As I tried to fix the remaining issues, I realized that the padding causes way too many issues. In `try-fix-#80-attempt-3`, I disabled it entirely. 
The consequence is rather big. The behavior changes when fully zoomed out. Now, even without any scroll offset, it's possible to scroll the map freely withing the screen bounds.
This new behavior ensures a consistent scrolling experience when scrolling in and out.

As for `setScrollOffsetRatio()`, I've tested it on various map sizes, and using different values (0.5f, 0.1f, etc). Looking good to me now. 
Again, thanks a lot for helping me to test.

**Comment by TimPushkin** [comment] 2022-11-26 20:42
I'm glad to help :) Played with it and haven't found any issues. With this behavior change perhaps it's a good idea to make `scroll(0.5, 0.5, Offset(-0.5f, -0.5f))` the default in `InitialValues` as most people probably expect their maps to appear in the center of the screen.

**Comment by p-lr** [comment] 2022-11-26 20:53
That's good point. I'll consider that. Thanks!

**Comment by p-lr** [comment] 2022-11-26 21:16
I've merged on master. Next I'll see if I can fix #79 before publishing the new `2.4.0` version.

**Closed** 2022-11-26 21:41 UTC
